# Generated by Django 5.0.6 on 2024-06-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FighterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_streak', models.IntegerField()),
                ('knockout_wins', models.IntegerField()),
                ('submission_wins', models.IntegerField()),
                ('sig_strikes_landed', models.IntegerField()),
                ('sig_strikes_attempted', models.IntegerField()),
                ('takedowns_landed', models.IntegerField()),
                ('takedowns_attempted', models.IntegerField()),
                ('sig_strikes_landed_per_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sig_strikes_absorbed_per_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('takedown_avg_per_15_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submission_avg_per_15_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sig_strike_defense', models.DecimalField(decimal_places=2, max_digits=5)),
                ('takedown_defense', models.DecimalField(decimal_places=2, max_digits=5)),
                ('knockdown_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_fight_time', models.DurationField()),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mma.fighter')),
            ],
        ),
    ]
