# Generated by Django 5.0.6 on 2024-06-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0002_fighterstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='FightHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('youtube_url', models.URLField()),
            ],
        ),
    ]
