# Generated by Django 5.0.6 on 2024-06-17 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0003_fighthighlight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fighterstats',
            name='organization',
            field=models.CharField(choices=[('UFC', 'UFC'), ('ONE FC', 'ONE FC'), ('ACA', 'ACA')], default='UFC', max_length=50),
        ),
        migrations.AddField(
            model_name='fighterstats',
            name='weight_class',
            field=models.CharField(choices=[('Musza', 'Musza – 56 kg'), ('Kogucia', 'Kogucia – 61 kg'), ('Piórkowa', 'Piórkowa – 65 kg'), ('Lekka', 'Lekka – 70 kg'), ('Półśrednia', 'Półśrednia – 77 kg'), ('Średnia', 'Średnia – 84 kg'), ('Półciężka', 'Półciężka – 93 kg'), ('Ciężka', 'Ciężka – powyżej 93 kg')], default='Musza', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='fights',
            field=models.ManyToManyField(related_name='events', to='mma.fight'),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mma.fight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BetPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
