# Generated by Django 5.0.6 on 2024-06-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0004_fighterstats_organization_fighterstats_weight_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fights',
        ),
        migrations.AddField(
            model_name='fight',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='mma.event'),
            preserve_default=False,
        ),
    ]
