# Generated by Django 5.0.6 on 2024-06-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mma', '0006_remove_fight_event_event_fights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betpoints',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='BetPoints',
        ),
    ]
